---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes


  - name: remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes

  - name: "install dependencies."
    become: yes
    apt:
      name: ["nodejs", "npm","tar","gzip","ansible"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: Creates directory
    file:
      path: ~/web
      state: directory

  - name: Extract backend into remote directory
    ansible.builtin.unarchive:
      src: ~/project/artifact.tar.gz
      dest: ~/web

  - name: run the backend
    become: true
    raw: ( cd ~/web && pm2 start npm -- start )   