---
  - name: "install dependencies."
    become: yes
    apt:
      name: ["nodejs", "npm","tar","gzip","ansible"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  # - name: Creates directory
  #   file:
  #     path: ~/web
  #     state: directory

  - name: Extract backend into remote directory
    ansible.builtin.unarchive:
      src: files/artifact.tar.gz
      dest: ~/

  # - name: run the backend
  #   become: true
  #   raw: ( cd ~/web && pm2 start npm -- start )  

  - name: run the backend
    become: true
    shell: |
      # cd ~/web
      npm install
      pm2 stop default
      pm2 start npm -- start 


    